<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\AdminController;
use App\Controllers\AdminBusinessDetailsController;
use App\Controllers\AdminEmployeesController;
use App\Controllers\AdminFormSelectValuesController;
use App\Controllers\AdminInvoiceItemTypesController;
use App\Controllers\AdminUsersController;
use App\Controllers\BillingController;
use App\Controllers\BoloController;
use App\Controllers\ClientsController;
use App\Controllers\ExpensesController;
use App\Controllers\HomeController;
use App\Controllers\JobsController;
use App\Controllers\PurchasesController;
use App\Controllers\ReportsController;
use App\Controllers\SettingsController;
use App\Controllers\SiteAdminController;
use App\Controllers\SalesController;
use App\Controllers\SearchController;
use App\Controllers\TasksController;
use App\Controllers\TimeTrackingController;
use App\Controllers\EventsController;
use Core\Router;

$router = new Router();

$router->get('/', [HomeController::class, 'index']);
$router->get('/reset-password/{token}', [AuthController::class, 'resetPasswordForm']);
$router->post('/reset-password/{token}', [AuthController::class, 'resetPassword']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'authenticate']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->get('/settings', [SettingsController::class, 'edit']);
$router->post('/settings/update', [SettingsController::class, 'update']);
$router->get('/search', [SearchController::class, 'index']);
$router->get('/events', [EventsController::class, 'index']);
$router->get('/events/feed', [EventsController::class, 'feed']);
$router->get('/events/{id}', [EventsController::class, 'show']);
$router->get('/events/{id}/json', [EventsController::class, 'json']);
$router->post('/events', [EventsController::class, 'store']);
$router->post('/events/{id}/update', [EventsController::class, 'update']);
$router->post('/events/{id}/cancel', [EventsController::class, 'cancel']);
$router->post('/events/{id}/move', [EventsController::class, 'move']);
$router->post('/events/{id}/delete', [EventsController::class, 'delete']);

$router->get('/site-admin/businesses', [SiteAdminController::class, 'businesses']);
$router->get('/site-admin/businesses/create', [SiteAdminController::class, 'createBusiness']);
$router->post('/site-admin/businesses', [SiteAdminController::class, 'storeBusiness']);
$router->get('/site-admin/businesses/{id}', [SiteAdminController::class, 'showBusiness']);
$router->get('/site-admin/businesses/{id}/edit', [SiteAdminController::class, 'editBusiness']);
$router->post('/site-admin/businesses/{id}/update', [SiteAdminController::class, 'updateBusiness']);
$router->post('/site-admin/businesses/{id}/toggle-active', [SiteAdminController::class, 'toggleBusinessActive']);
$router->post('/site-admin/switch-business', [SiteAdminController::class, 'switchBusiness']);
$router->post('/site-admin/exit-workspace', [SiteAdminController::class, 'exitWorkspace']);

$router->get('/bolo', [BoloController::class, 'index']);

$router->get('/clients', [ClientsController::class, 'index']);
$router->get('/clients/create', [ClientsController::class, 'create']);
$router->post('/clients', [ClientsController::class, 'store']);
$router->get('/clients/{id}/edit', [ClientsController::class, 'edit']);
$router->post('/clients/{id}/update', [ClientsController::class, 'update']);
$router->post('/clients/{id}/deactivate', [ClientsController::class, 'deactivate']);
$router->get('/clients/{id}/contacts/create', [ClientsController::class, 'createContact']);
$router->post('/clients/{id}/contacts', [ClientsController::class, 'storeContact']);
$router->get('/clients/{id}/bolo/edit', [ClientsController::class, 'editBolo']);
$router->post('/clients/{id}/bolo/deactivate', [ClientsController::class, 'deactivateBolo']);
$router->post('/clients/{id}/bolo/reactivate', [ClientsController::class, 'reactivateBolo']);
$router->post('/clients/{id}/bolo', [ClientsController::class, 'updateBolo']);
$router->get('/clients/{id}', [ClientsController::class, 'show']);

$router->get('/expenses', [ExpensesController::class, 'index']);
$router->get('/expenses/create', [ExpensesController::class, 'create']);
$router->post('/expenses', [ExpensesController::class, 'store']);
$router->get('/expenses/{id}/edit', [ExpensesController::class, 'edit']);
$router->post('/expenses/{id}/update', [ExpensesController::class, 'update']);
$router->post('/expenses/{id}/delete', [ExpensesController::class, 'delete']);
$router->get('/expenses/{id}', [ExpensesController::class, 'show']);

$router->get('/jobs', [JobsController::class, 'index']);
$router->get('/jobs/create', [JobsController::class, 'create']);
$router->post('/jobs', [JobsController::class, 'store']);
$router->get('/jobs/client-search', [JobsController::class, 'clientSearch']);
$router->post('/jobs/quick-create-client', [JobsController::class, 'quickCreateClient']);
$router->get('/jobs/{id}/edit', [JobsController::class, 'edit']);
$router->post('/jobs/{id}/update', [JobsController::class, 'update']);
$router->post('/jobs/{id}/deactivate', [JobsController::class, 'deactivate']);
$router->get('/jobs/{id}/expenses/create', [JobsController::class, 'createExpense']);
$router->post('/jobs/{id}/expenses', [JobsController::class, 'storeExpense']);
$router->get('/jobs/{id}/expenses/{expenseId}', [JobsController::class, 'showExpense']);
$router->get('/jobs/{id}/expenses/{expenseId}/edit', [JobsController::class, 'editExpense']);
$router->post('/jobs/{id}/expenses/{expenseId}/update', [JobsController::class, 'updateExpense']);
$router->post('/jobs/{id}/expenses/{expenseId}/delete', [JobsController::class, 'deleteExpense']);
$router->get('/jobs/{id}/adjustments/create', [JobsController::class, 'createAdjustment']);
$router->post('/jobs/{id}/adjustments', [JobsController::class, 'storeAdjustment']);
$router->get('/jobs/{id}/adjustments/{adjustmentId}/edit', [JobsController::class, 'editAdjustment']);
$router->post('/jobs/{id}/adjustments/{adjustmentId}/update', [JobsController::class, 'updateAdjustment']);
$router->post('/jobs/{id}/adjustments/{adjustmentId}/delete', [JobsController::class, 'deleteAdjustment']);
$router->get('/jobs/{id}/adjustments/{adjustmentId}', [JobsController::class, 'showAdjustment']);
$router->get('/jobs/{id}/employees/add', [JobsController::class, 'addEmployee']);
$router->get('/jobs/{id}/employees/search', [JobsController::class, 'employeeSearch']);
$router->post('/jobs/{id}/employees', [JobsController::class, 'storeEmployee']);
$router->post('/jobs/{id}/employees/{employeeId}/punch-in', [JobsController::class, 'punchInEmployee']);
$router->post('/jobs/{id}/employees/{employeeId}/punch-out', [JobsController::class, 'punchOutEmployee']);
$router->get('/jobs/{id}', [JobsController::class, 'show']);

$router->get('/tasks', [TasksController::class, 'index']);
$router->get('/tasks/create', [TasksController::class, 'create']);
$router->post('/tasks', [TasksController::class, 'store']);
$router->post('/tasks/quick-create', [TasksController::class, 'quickCreate']);
$router->post('/tasks/{id}/quick-complete', [TasksController::class, 'quickComplete']);
$router->post('/tasks/{id}/quick-status', [TasksController::class, 'quickStatus']);
$router->post('/tasks/{id}/quick-take-ownership', [TasksController::class, 'quickTakeOwnership']);
$router->post('/tasks/{id}/take-ownership', [TasksController::class, 'takeOwnership']);
$router->get('/tasks/{id}/edit', [TasksController::class, 'edit']);
$router->post('/tasks/{id}/update', [TasksController::class, 'update']);
$router->get('/tasks/{id}', [TasksController::class, 'show']);

$router->get('/time-tracking', [TimeTrackingController::class, 'index']);
$router->get('/time-tracking/punch-board', [TimeTrackingController::class, 'punchBoard']);
$router->get('/punch-board', [TimeTrackingController::class, 'punchBoard']);
$router->get('/time-tracking/create', [TimeTrackingController::class, 'create']);
$router->get('/time-tracking/job-search', [TimeTrackingController::class, 'jobSearch']);
$router->post('/time-tracking', [TimeTrackingController::class, 'store']);
$router->post('/time-tracking/punch-in', [TimeTrackingController::class, 'punchIn']);
$router->post('/time-tracking/punch-out', [TimeTrackingController::class, 'punchOut']);
$router->get('/time-tracking/{id}/edit', [TimeTrackingController::class, 'edit']);
$router->post('/time-tracking/{id}/update', [TimeTrackingController::class, 'update']);
$router->post('/time-tracking/{id}/delete', [TimeTrackingController::class, 'delete']);
$router->get('/time-tracking/{id}', [TimeTrackingController::class, 'show']);

$router->get('/billing', [BillingController::class, 'index']);
$router->get('/billing/create', [BillingController::class, 'create']);
$router->post('/billing', [BillingController::class, 'store']);
$router->get('/billing/payments/create', [BillingController::class, 'createPayment']);
$router->post('/billing/payments', [BillingController::class, 'storePayment']);
$router->get('/billing/payments/{id}/edit', [BillingController::class, 'editPayment']);
$router->post('/billing/payments/{id}/update', [BillingController::class, 'updatePayment']);
$router->post('/billing/payments/{id}/delete', [BillingController::class, 'deletePayment']);
$router->get('/billing/payments/{id}', [BillingController::class, 'showPayment']);
$router->get('/billing/{id}/edit', [BillingController::class, 'edit']);
$router->post('/billing/{id}/update', [BillingController::class, 'update']);
$router->post('/billing/{id}/quick-status', [BillingController::class, 'quickStatus']);
$router->post('/billing/{id}/delete', [BillingController::class, 'delete']);
$router->get('/billing/{id}', [BillingController::class, 'show']);

$router->get('/sales', [SalesController::class, 'index']);
$router->get('/sales/create', [SalesController::class, 'create']);
$router->post('/sales', [SalesController::class, 'store']);
$router->get('/sales/client-search', [SalesController::class, 'clientSearch']);
$router->get('/sales/job-search', [SalesController::class, 'jobSearch']);
$router->get('/sales/purchase-search', [SalesController::class, 'purchaseSearch']);
$router->get('/sales/{id}/edit', [SalesController::class, 'edit']);
$router->post('/sales/{id}/update', [SalesController::class, 'update']);
$router->post('/sales/{id}/delete', [SalesController::class, 'delete']);
$router->get('/sales/{id}', [SalesController::class, 'show']);

$router->get('/reports', [ReportsController::class, 'index']);

$router->get('/purchases', [PurchasesController::class, 'index']);
$router->get('/purchases/create', [PurchasesController::class, 'create']);
$router->post('/purchases', [PurchasesController::class, 'store']);
$router->get('/purchases/client-search', [PurchasesController::class, 'clientSearch']);
$router->post('/purchases/quick-create-client', [PurchasesController::class, 'quickCreateClient']);
$router->get('/purchases/{id}/edit', [PurchasesController::class, 'edit']);
$router->post('/purchases/{id}/update', [PurchasesController::class, 'update']);
$router->post('/purchases/{id}/delete', [PurchasesController::class, 'delete']);
$router->get('/purchases/{id}', [PurchasesController::class, 'show']);

$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/business-details', [AdminBusinessDetailsController::class, 'edit']);
$router->post('/admin/business-details/update', [AdminBusinessDetailsController::class, 'update']);
$router->get('/admin/users', [AdminUsersController::class, 'index']);
$router->get('/admin/users/create', [AdminUsersController::class, 'create']);
$router->post('/admin/users', [AdminUsersController::class, 'store']);
$router->get('/admin/users/{id}/edit', [AdminUsersController::class, 'edit']);
$router->post('/admin/users/{id}/update', [AdminUsersController::class, 'update']);
$router->post('/admin/users/{id}/toggle-active', [AdminUsersController::class, 'toggleActive']);
$router->post('/admin/users/{id}/resend-invite', [AdminUsersController::class, 'resendInvite']);
$router->post('/admin/users/{id}/send-password-reset', [AdminUsersController::class, 'sendPasswordReset']);
$router->post('/admin/users/{id}/auto-accept', [AdminUsersController::class, 'autoAccept']);
$router->get('/admin/employees', [AdminEmployeesController::class, 'index']);
$router->get('/admin/employees/create', [AdminEmployeesController::class, 'create']);
$router->post('/admin/employees', [AdminEmployeesController::class, 'store']);
$router->get('/admin/employees/{id}/edit', [AdminEmployeesController::class, 'edit']);
$router->post('/admin/employees/{id}/update', [AdminEmployeesController::class, 'update']);
$router->get('/admin/employees/{id}', [AdminEmployeesController::class, 'show']);
$router->get('/admin/invoice-item-types', [AdminInvoiceItemTypesController::class, 'index']);
$router->get('/admin/invoice-item-types/create', [AdminInvoiceItemTypesController::class, 'create']);
$router->post('/admin/invoice-item-types', [AdminInvoiceItemTypesController::class, 'store']);
$router->get('/admin/invoice-item-types/{id}/edit', [AdminInvoiceItemTypesController::class, 'edit']);
$router->post('/admin/invoice-item-types/{id}/update', [AdminInvoiceItemTypesController::class, 'update']);
$router->post('/admin/invoice-item-types/{id}/delete', [AdminInvoiceItemTypesController::class, 'delete']);
$router->get('/admin/form-select-values', [AdminFormSelectValuesController::class, 'index']);
$router->get('/admin/form-select-values/{formKey}', [AdminFormSelectValuesController::class, 'show']);
$router->post('/admin/form-select-values/quick-create', [AdminFormSelectValuesController::class, 'quickCreate']);
$router->post('/admin/form-select-values/{id}/quick-update', [AdminFormSelectValuesController::class, 'quickUpdate']);
$router->post('/admin/form-select-values/{id}/quick-delete', [AdminFormSelectValuesController::class, 'quickDelete']);

return $router;
