<?php

declare(strict_types=1);

use Core\Router;
use App\Controllers\AdminController;
use App\Controllers\AdminAuditController;
use App\Controllers\AdminBusinessInfoController;
use App\Controllers\AdminLookupsController;
use App\Controllers\AdminPermissionsController;
use App\Controllers\AdminRecoveryController;
use App\Controllers\AdminSettingsController;
use App\Controllers\HomeController;
use App\Controllers\AuthController;
use App\Controllers\AttachmentsController;
use App\Controllers\DataQualityController;
use App\Controllers\ErrorController;
use App\Controllers\FilterPresetsController;
use App\Controllers\PagesController;
use App\Controllers\PhotosController;
use App\Controllers\JobDocumentsController;
use App\Controllers\NotificationsController;
use App\Controllers\ReportsController;
use App\Controllers\SearchController;
use App\Controllers\SettingsController;
use App\Controllers\SiteAdminSupportController;
use App\Controllers\SiteAdminController;
use App\Controllers\SiteSupportController;
use App\Controllers\SchedulingController;
use App\Controllers\UsersController;
use App\Controllers\JobsController;
use App\Controllers\ExpensesController;
use App\Controllers\SalesController;
use App\Controllers\TasksController;
use App\Controllers\EmployeesController;
use App\Controllers\TimeTrackingController;
use App\Controllers\ClientsController;
use App\Controllers\ConsignorsController;
use App\Controllers\ProspectsController;
use App\Controllers\ClientContactsController;
use App\Controllers\ContactsController;
use App\Controllers\CompaniesController;
use App\Controllers\EstatesController;
use App\Controllers\DisposalLocationsController;
use App\Controllers\DevController;
use App\Controllers\ExpenseCategoriesController;

$router = new Router();

$router->get('/', [HomeController::class, 'index']);
$router->post('/dashboard/punch-in', [HomeController::class, 'punchInSelf']);
$router->post('/dashboard/punch-out', [HomeController::class, 'punchOutSelf']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'authenticate']);
$router->get('/login/2fa', [AuthController::class, 'twoFactor']);
$router->post('/login/2fa', [AuthController::class, 'verifyTwoFactor']);
$router->post('/login/2fa/resend', [AuthController::class, 'resendTwoFactor']);
$router->get('/set-password', [AuthController::class, 'showSetPassword']);
$router->post('/set-password', [AuthController::class, 'storeSetPassword']);
$router->get('/register', [AuthController::class, 'register']);
$router->get('/forgot-password', [AuthController::class, 'forgot']);
$router->get('/privacy-policy', [PagesController::class, 'privacyPolicy']);
$router->get('/terms-and-conditions', [PagesController::class, 'termsAndConditions']);
$router->post('/logout', [AuthController::class, 'logout']);
$router->post('/filter-presets/save', [FilterPresetsController::class, 'save']);
$router->post('/filter-presets/{id}/delete', [FilterPresetsController::class, 'delete']);

$router->get('/charts', [PagesController::class, 'charts']);
$router->get('/tables', [PagesController::class, 'tables']);
$router->get('/search', [SearchController::class, 'index']);
$router->get('/notifications', [NotificationsController::class, 'index']);
$router->get('/notifications/summary', [NotificationsController::class, 'summary']);
$router->get('/notifications/open', [NotificationsController::class, 'open']);
$router->post('/notifications/read', [NotificationsController::class, 'read']);
$router->post('/notifications/read-all', [NotificationsController::class, 'readAll']);
$router->post('/notifications/dismiss', [NotificationsController::class, 'dismiss']);
$router->get('/reports', [ReportsController::class, 'index']);
$router->get('/photos', [PhotosController::class, 'index']);
$router->post('/photos/download', [PhotosController::class, 'downloadSelected']);
$router->post('/reports/presets/save', [ReportsController::class, 'savePreset']);
$router->post('/reports/presets/{id}/delete', [ReportsController::class, 'deletePreset']);
$router->get('/data-quality', [DataQualityController::class, 'index']);
$router->post('/data-quality/merge/client', [DataQualityController::class, 'mergeClient']);
$router->post('/data-quality/merge/company', [DataQualityController::class, 'mergeCompany']);
$router->post('/data-quality/merge/job', [DataQualityController::class, 'mergeJob']);
$router->post('/attachments/upload', [AttachmentsController::class, 'upload']);
$router->get('/attachments/{id}/download', [AttachmentsController::class, 'download']);
$router->post('/attachments/{id}/label', [AttachmentsController::class, 'updateLabel']);
$router->post('/attachments/{id}/delete', [AttachmentsController::class, 'delete']);
$router->get('/settings', [SettingsController::class, 'edit']);
$router->post('/settings', [SettingsController::class, 'update']);
$router->get('/activity-log', [UsersController::class, 'myActivity']);
$router->get('/support', [SiteSupportController::class, 'index']);
$router->get('/support/new', [SiteSupportController::class, 'create']);
$router->post('/support/new', [SiteSupportController::class, 'store']);
$router->get('/support/{id}', [SiteSupportController::class, 'show']);
$router->post('/support/{id}/notes', [SiteSupportController::class, 'addNote']);
$router->get('/dev', [DevController::class, 'index']);
$router->get('/dev/bugs', [DevController::class, 'bugs']);
$router->post('/dev/bugs/new', [DevController::class, 'storeBug']);
$router->get('/dev/bugs/{id}', [DevController::class, 'showBug']);
$router->post('/dev/bugs/{id}/update', [DevController::class, 'updateBug']);
$router->post('/dev/bugs/{id}/status', [DevController::class, 'updateBugStatus']);
$router->post('/dev/bugs/{id}/notes', [DevController::class, 'addBugNote']);
$router->post('/dev/bugs/{id}/delete', [DevController::class, 'deleteBug']);
$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/permissions', [AdminPermissionsController::class, 'index']);
$router->post('/admin/permissions', [AdminPermissionsController::class, 'update']);
$router->get('/admin/settings', [AdminSettingsController::class, 'index']);
$router->post('/admin/settings', [AdminSettingsController::class, 'update']);
$router->post('/admin/settings/test-email', [AdminSettingsController::class, 'sendTestEmail']);
$router->get('/admin/business-info', [AdminBusinessInfoController::class, 'index']);
$router->post('/admin/business-info', [AdminBusinessInfoController::class, 'update']);
$router->get('/admin/audit', [AdminAuditController::class, 'index']);
$router->get('/admin/recovery', [AdminRecoveryController::class, 'index']);
$router->post('/admin/recovery/{entity}/{id}/restore', [AdminRecoveryController::class, 'restore']);
$router->get('/admin/lookups', [AdminLookupsController::class, 'index']);
$router->get('/admin/lookups/new', [AdminLookupsController::class, 'create']);
$router->post('/admin/lookups/new', [AdminLookupsController::class, 'store']);
$router->get('/admin/lookups/{id}/edit', [AdminLookupsController::class, 'edit']);
$router->post('/admin/lookups/{id}/edit', [AdminLookupsController::class, 'update']);
$router->post('/admin/lookups/{id}/delete', [AdminLookupsController::class, 'delete']);
$router->get('/site-admin', [SiteAdminController::class, 'index']);
$router->get('/site-admin/businesses/{id}', [SiteAdminController::class, 'showBusiness']);
$router->get('/site-admin/businesses/{id}/edit', [SiteAdminController::class, 'editBusiness']);
$router->post('/site-admin/businesses', [SiteAdminController::class, 'storeBusiness']);
$router->post('/site-admin/businesses/{id}/edit', [SiteAdminController::class, 'updateBusiness']);
$router->post('/site-admin/switch-business', [SiteAdminController::class, 'switchBusiness']);
$router->get('/site-admin/support', [SiteAdminSupportController::class, 'index']);
$router->get('/site-admin/support/{id}', [SiteAdminSupportController::class, 'show']);
$router->post('/site-admin/support/{id}/update', [SiteAdminSupportController::class, 'update']);
$router->post('/site-admin/support/{id}/pickup', [SiteAdminSupportController::class, 'pickup']);
$router->post('/site-admin/support/{id}/notes', [SiteAdminSupportController::class, 'addNote']);
$router->post('/site-admin/support/{id}/convert-bug', [SiteAdminSupportController::class, 'convertBug']);

$router->get('/jobs', [JobsController::class, 'index']);
$router->get('/jobs/schedule', [SchedulingController::class, 'index']);
$router->get('/jobs/schedule/events', [SchedulingController::class, 'events']);
$router->post('/jobs/schedule/update', [SchedulingController::class, 'update']);
$router->get('/jobs/new', [JobsController::class, 'create']);
$router->post('/jobs/new', [JobsController::class, 'store']);
$router->get('/expenses', [ExpensesController::class, 'index']);
$router->get('/expenses/lookup/jobs', [ExpensesController::class, 'jobLookup']);
$router->get('/expenses/new', [ExpensesController::class, 'create']);
$router->post('/expenses/new', [ExpensesController::class, 'store']);
$router->get('/tasks', [TasksController::class, 'index']);
$router->get('/tasks/lookup/links', [TasksController::class, 'linkLookup']);
$router->get('/tasks/new', [TasksController::class, 'create']);
$router->post('/tasks/new', [TasksController::class, 'store']);
$router->get('/tasks/{id}/edit', [TasksController::class, 'edit']);
$router->post('/tasks/{id}/edit', [TasksController::class, 'update']);
$router->post('/tasks/{id}/toggle-complete', [TasksController::class, 'toggleComplete']);
$router->post('/tasks/{id}/assignment/respond', [TasksController::class, 'respondAssignment']);
$router->post('/tasks/{id}/delete', [TasksController::class, 'delete']);
$router->get('/tasks/{id}', [TasksController::class, 'show']);
$router->get('/employees', [EmployeesController::class, 'index']);
$router->get('/employees/new', [EmployeesController::class, 'create']);
$router->post('/employees/new', [EmployeesController::class, 'store']);
$router->get('/employees/{id}/edit', [EmployeesController::class, 'edit']);
$router->post('/employees/{id}/edit', [EmployeesController::class, 'update']);
$router->post('/employees/{id}/punch-in', [EmployeesController::class, 'punchIn']);
$router->post('/employees/{id}/punch-out', [EmployeesController::class, 'punchOut']);
$router->get('/employees/{id}', [EmployeesController::class, 'show']);
$router->get('/time-tracking', [TimeTrackingController::class, 'index']);
$router->get('/time-tracking/open', [TimeTrackingController::class, 'open']);
$router->get('/punch-clock', [TimeTrackingController::class, 'open']);
$router->post('/time-tracking/open/punch-in', [TimeTrackingController::class, 'openPunchIn']);
$router->get('/time-tracking/lookup/employees', [TimeTrackingController::class, 'employeeLookup']);
$router->get('/time-tracking/lookup/jobs', [TimeTrackingController::class, 'jobLookup']);
$router->get('/time-tracking/new', [TimeTrackingController::class, 'create']);
$router->post('/time-tracking/new', [TimeTrackingController::class, 'store']);
$router->post('/time-tracking/{id}/punch-out', [TimeTrackingController::class, 'punchOut']);
$router->get('/time-tracking/{id}/edit', [TimeTrackingController::class, 'edit']);
$router->post('/time-tracking/{id}/edit', [TimeTrackingController::class, 'update']);
$router->post('/time-tracking/{id}/delete', [TimeTrackingController::class, 'delete']);
$router->get('/time-tracking/{id}', [TimeTrackingController::class, 'show']);
$router->get('/sales', [SalesController::class, 'index']);
$router->get('/sales/new', [SalesController::class, 'create']);
$router->post('/sales/new', [SalesController::class, 'store']);
$router->get('/sales/lookup/jobs', [SalesController::class, 'jobLookup']);
$router->get('/sales/lookup/scrap-yards', [SalesController::class, 'scrapYardLookup']);
$router->get('/sales/{id}/edit', [SalesController::class, 'edit']);
$router->post('/sales/{id}/edit', [SalesController::class, 'update']);
$router->post('/sales/{id}/delete', [SalesController::class, 'delete']);
$router->get('/sales/{id}', [SalesController::class, 'show']);
$router->get('/jobs/lookup/owners', [JobsController::class, 'ownerLookup']);
$router->get('/jobs/lookup/contacts', [JobsController::class, 'contactLookup']);
$router->get('/jobs/{id}/crew/lookup', [JobsController::class, 'crewLookup']);
$router->post('/jobs/{id}/crew/add', [JobsController::class, 'crewAdd']);
$router->post('/jobs/{id}/crew/{employeeId}/remove', [JobsController::class, 'crewRemove']);
$router->post('/jobs/{id}/time/punch-in', [JobsController::class, 'punchIn']);
$router->post('/jobs/{id}/time/punch-out', [JobsController::class, 'punchOut']);
$router->get('/jobs/{id}/documents/new', [JobDocumentsController::class, 'create']);
$router->post('/jobs/{id}/documents/new', [JobDocumentsController::class, 'store']);
$router->get('/jobs/{id}/documents/{documentId}/edit', [JobDocumentsController::class, 'edit']);
$router->post('/jobs/{id}/documents/{documentId}/edit', [JobDocumentsController::class, 'update']);
$router->post('/jobs/{id}/documents/{documentId}/delete', [JobDocumentsController::class, 'delete']);
$router->get('/jobs/{id}/documents/{documentId}/pdf', [JobDocumentsController::class, 'pdf']);
$router->get('/jobs/{id}/documents/{documentId}', [JobDocumentsController::class, 'show']);
$router->get('/jobs/{id}', [JobsController::class, 'show']);
$router->get('/jobs/{id}/edit', [JobsController::class, 'edit']);
$router->post('/jobs/{id}/edit', [JobsController::class, 'update']);

$router->get('/jobs/{id}/actions/new', [JobsController::class, 'actionCreate']);
$router->post('/jobs/{id}/actions/new', [JobsController::class, 'actionStore']);
$router->get('/jobs/{id}/actions/{actionId}/edit', [JobsController::class, 'actionEdit']);
$router->post('/jobs/{id}/actions/{actionId}/edit', [JobsController::class, 'actionUpdate']);
$router->post('/jobs/{id}/actions/{actionId}/delete', [JobsController::class, 'actionDelete']);

$router->get('/jobs/{id}/disposals/new', [JobsController::class, 'disposalCreate']);
$router->post('/jobs/{id}/disposals/new', [JobsController::class, 'disposalStore']);
$router->get('/jobs/{id}/disposals/{disposalId}/edit', [JobsController::class, 'disposalEdit']);
$router->post('/jobs/{id}/disposals/{disposalId}/edit', [JobsController::class, 'disposalUpdate']);
$router->post('/jobs/{id}/disposals/{disposalId}/delete', [JobsController::class, 'disposalDelete']);

$router->get('/jobs/{id}/expenses/new', [JobsController::class, 'expenseCreate']);
$router->post('/jobs/{id}/expenses/new', [JobsController::class, 'expenseStore']);
$router->get('/jobs/{id}/expenses/{expenseId}/edit', [JobsController::class, 'expenseEdit']);
$router->post('/jobs/{id}/expenses/{expenseId}/edit', [JobsController::class, 'expenseUpdate']);
$router->post('/jobs/{id}/expenses/{expenseId}/delete', [JobsController::class, 'expenseDelete']);

$router->get('/jobs/{id}/billing/new', [JobsController::class, 'billingCreate']);
$router->post('/jobs/{id}/billing/new', [JobsController::class, 'billingStore']);
$router->get('/jobs/{id}/billing/{billingId}/edit', [JobsController::class, 'billingEdit']);
$router->post('/jobs/{id}/billing/{billingId}/edit', [JobsController::class, 'billingUpdate']);
$router->post('/jobs/{id}/billing/{billingId}/delete', [JobsController::class, 'billingDelete']);
$router->post('/jobs/{id}/mark-paid', [JobsController::class, 'markPaid']);
$router->post('/jobs/{id}/status', [JobsController::class, 'updateStatus']);
$router->post('/jobs/{id}/delete', [JobsController::class, 'delete']);

$router->get('/users', [UsersController::class, 'index']);
$router->get('/users/new', [UsersController::class, 'create']);
$router->get('/users/lookup/employees', [UsersController::class, 'employeeLookup']);
$router->get('/users/{id}/edit', [UsersController::class, 'edit']);
$router->get('/users/{id}/activity', [UsersController::class, 'activity']);
$router->get('/users/{id}/logins', [UsersController::class, 'logins']);
$router->get('/users/{id}', [UsersController::class, 'show']);
$router->post('/users', [UsersController::class, 'store']);
$router->post('/users/{id}', [UsersController::class, 'update']);
$router->post('/users/{id}/employee-link', [UsersController::class, 'linkEmployee']);
$router->post('/users/{id}/employee-unlink', [UsersController::class, 'unlinkEmployee']);
$router->post('/users/{id}/invite-auto-accept', [UsersController::class, 'autoAcceptInvite']);
$router->post('/users/{id}/deactivate', [UsersController::class, 'deactivate']);

$router->get('/clients', [ClientsController::class, 'index']);
$router->get('/clients/lookup', [ClientsController::class, 'lookup']);
$router->get('/clients/lookup/companies', [ClientsController::class, 'companyLookup']);
$router->get('/clients/duplicate-check', [ClientsController::class, 'duplicateCheck']);
$router->post('/clients/quick-create', [ClientsController::class, 'quickCreate']);
$router->get('/clients/new', [ClientsController::class, 'create']);
$router->post('/clients/new', [ClientsController::class, 'store']);
$router->get('/clients/{id}/edit', [ClientsController::class, 'edit']);
$router->post('/clients/{id}/edit', [ClientsController::class, 'update']);
$router->post('/clients/{id}/deactivate', [ClientsController::class, 'deactivate']);
$router->post('/clients/{id}/save-contact', [ClientsController::class, 'saveAsContact']);
$router->get('/clients/{id}', [ClientsController::class, 'show']);

$router->get('/consignors', [ConsignorsController::class, 'index']);
$router->get('/consignors/new', [ConsignorsController::class, 'create']);
$router->post('/consignors/new', [ConsignorsController::class, 'store']);
$router->get('/consignors/{id}/edit', [ConsignorsController::class, 'edit']);
$router->post('/consignors/{id}/edit', [ConsignorsController::class, 'update']);
$router->post('/consignors/{id}/deactivate', [ConsignorsController::class, 'deactivate']);
$router->post('/consignors/{id}/contacts/new', [ConsignorsController::class, 'addContact']);
$router->post('/consignors/{id}/contracts/new', [ConsignorsController::class, 'addContract']);
$router->post('/consignors/{id}/contracts/{contractId}/delete', [ConsignorsController::class, 'deleteContract']);
$router->get('/consignors/{id}/contracts/{contractId}/download', [ConsignorsController::class, 'downloadContract']);
$router->post('/consignors/{id}/payouts/new', [ConsignorsController::class, 'addPayout']);
$router->get('/consignors/{id}', [ConsignorsController::class, 'show']);

$router->get('/prospects', [ProspectsController::class, 'index']);
$router->get('/prospects/lookup/clients', [ProspectsController::class, 'clientLookup']);
$router->get('/prospects/{id}/convert', [ProspectsController::class, 'convert']);
$router->get('/prospects/new', [ProspectsController::class, 'create']);
$router->post('/prospects/new', [ProspectsController::class, 'store']);
$router->get('/prospects/{id}/edit', [ProspectsController::class, 'edit']);
$router->post('/prospects/{id}/edit', [ProspectsController::class, 'update']);
$router->post('/prospects/{id}/delete', [ProspectsController::class, 'delete']);
$router->get('/prospects/{id}', [ProspectsController::class, 'show']);

$router->get('/client-contacts', [ClientContactsController::class, 'index']);
$router->get('/client-contacts/new', [ClientContactsController::class, 'create']);
$router->post('/client-contacts/new', [ClientContactsController::class, 'store']);
$router->get('/client-contacts/{id}', [ClientContactsController::class, 'show']);

$router->get('/contacts', [ContactsController::class, 'index']);
$router->get('/contacts/lookup/companies', [ContactsController::class, 'companyLookup']);
$router->get('/contacts/new', [ContactsController::class, 'create']);
$router->post('/contacts/new', [ContactsController::class, 'store']);
$router->get('/contacts/{id}/edit', [ContactsController::class, 'edit']);
$router->post('/contacts/{id}/edit', [ContactsController::class, 'update']);
$router->post('/contacts/{id}/deactivate', [ContactsController::class, 'deactivate']);
$router->post('/contacts/{id}/create-client', [ContactsController::class, 'createClient']);
$router->get('/contacts/{id}', [ContactsController::class, 'show']);
$router->get('/network', [ContactsController::class, 'index']);
$router->get('/network/lookup/companies', [ContactsController::class, 'companyLookup']);
$router->get('/network/new', [ContactsController::class, 'create']);
$router->post('/network/new', [ContactsController::class, 'store']);
$router->get('/network/{id}/edit', [ContactsController::class, 'edit']);
$router->post('/network/{id}/edit', [ContactsController::class, 'update']);
$router->post('/network/{id}/deactivate', [ContactsController::class, 'deactivate']);
$router->post('/network/{id}/create-client', [ContactsController::class, 'createClient']);
$router->get('/network/{id}', [ContactsController::class, 'show']);

$router->get('/companies', [CompaniesController::class, 'index']);
$router->get('/companies/lookup', [CompaniesController::class, 'lookup']);
$router->post('/companies/quick-create', [CompaniesController::class, 'quickCreate']);
$router->get('/companies/new', [CompaniesController::class, 'create']);
$router->post('/companies/new', [CompaniesController::class, 'store']);
$router->get('/companies/{id}/edit', [CompaniesController::class, 'edit']);
$router->post('/companies/{id}/edit', [CompaniesController::class, 'update']);
$router->post('/companies/{id}/delete', [CompaniesController::class, 'delete']);
$router->get('/companies/{id}', [CompaniesController::class, 'show']);

$router->get('/estates', [EstatesController::class, 'index']);
$router->get('/estates/lookup', [EstatesController::class, 'lookup']);
$router->get('/estates/new', [EstatesController::class, 'create']);
$router->post('/estates/new', [EstatesController::class, 'store']);
$router->get('/estates/{id}/edit', [EstatesController::class, 'edit']);
$router->post('/estates/{id}/edit', [EstatesController::class, 'update']);
$router->get('/estates/{id}', [EstatesController::class, 'show']);

$router->get('/admin/disposal-locations', [DisposalLocationsController::class, 'index']);
$router->get('/admin/disposal-locations/new', [DisposalLocationsController::class, 'create']);
$router->post('/admin/disposal-locations/new', [DisposalLocationsController::class, 'store']);
$router->get('/admin/disposal-locations/{id}/edit', [DisposalLocationsController::class, 'edit']);
$router->post('/admin/disposal-locations/{id}/edit', [DisposalLocationsController::class, 'update']);
$router->post('/admin/disposal-locations/{id}/delete', [DisposalLocationsController::class, 'delete']);

$router->get('/admin/expense-categories', [ExpenseCategoriesController::class, 'index']);
$router->get('/admin/expense-categories/new', [ExpenseCategoriesController::class, 'create']);
$router->post('/admin/expense-categories/new', [ExpenseCategoriesController::class, 'store']);
$router->get('/admin/expense-categories/{id}/edit', [ExpenseCategoriesController::class, 'edit']);
$router->post('/admin/expense-categories/{id}/edit', [ExpenseCategoriesController::class, 'update']);
$router->post('/admin/expense-categories/{id}/delete', [ExpenseCategoriesController::class, 'delete']);

$router->get('/401', [ErrorController::class, 'unauthorized']);
$router->get('/404', [ErrorController::class, 'notFound']);
$router->get('/500', [ErrorController::class, 'serverError']);

return $router;
