-- JunkTracker: refresh role permission defaults after Beta 1.2 updates
-- Adds/updates permission rows for all current modules, including dev_tools.
-- Dev tools remain restricted to role 99 in application logic; role table keeps it disabled for 1/2/3.

CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    role_value SMALLINT UNSIGNED NOT NULL,
    module_key VARCHAR(80) NOT NULL,
    can_view TINYINT(1) NOT NULL DEFAULT 1,
    can_create TINYINT(1) NOT NULL DEFAULT 1,
    can_edit TINYINT(1) NOT NULL DEFAULT 1,
    can_delete TINYINT(1) NOT NULL DEFAULT 1,
    updated_by BIGINT UNSIGNED NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_role_permissions_role_module (role_value, module_key),
    KEY idx_role_permissions_module (module_key),
    KEY idx_role_permissions_updated_by (updated_by),
    CONSTRAINT fk_role_permissions_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Role 1
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'dashboard', 1, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'jobs', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'prospects', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'sales', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'customers', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'clients', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'estates', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'companies', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'client_contacts', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'consignors', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'time_tracking', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'expenses', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'tasks', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'employees', 1, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'admin', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'users', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'expense_categories', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'disposal_locations', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'admin_settings', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'audit_log', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'recovery', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'lookups', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'permissions', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (1, 'dev_tools', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();

-- Role 2
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'dashboard', 1, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'jobs', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'prospects', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'sales', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'customers', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'clients', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'estates', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'companies', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'client_contacts', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'consignors', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'time_tracking', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'expenses', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'tasks', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'employees', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'admin', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'users', 1, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'expense_categories', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'disposal_locations', 1, 1, 1, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'admin_settings', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'audit_log', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'recovery', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'lookups', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'permissions', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (2, 'dev_tools', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();

-- Role 3
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'dashboard', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'jobs', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'prospects', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'sales', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'customers', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'clients', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'estates', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'companies', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'client_contacts', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'consignors', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'time_tracking', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'expenses', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'tasks', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'employees', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'admin', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'users', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'expense_categories', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'disposal_locations', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'admin_settings', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'audit_log', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'recovery', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'lookups', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'permissions', 1, 1, 1, 1, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();
INSERT INTO role_permissions (role_value, module_key, can_view, can_create, can_edit, can_delete, updated_by, updated_at) VALUES (3, 'dev_tools', 0, 0, 0, 0, NULL, NOW()) ON DUPLICATE KEY UPDATE can_view = VALUES(can_view), can_create = VALUES(can_create), can_edit = VALUES(can_edit), can_delete = VALUES(can_delete), updated_by = VALUES(updated_by), updated_at = NOW();

CREATE TABLE IF NOT EXISTS schema_migrations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    migration_key VARCHAR(190) NOT NULL,
    checksum VARCHAR(64) NULL,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_schema_migrations_key (migration_key),
    KEY idx_schema_migrations_applied_at (applied_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO schema_migrations (migration_key, checksum, applied_at) VALUES
('2026-02-20_role_permissions_beta_1_2_refresh', 'roles-beta-1.2-refresh-v1', NOW());
